Repository facebookresearch/spot-sim2real, pull requests merged in 2023-09, with the labels that each got.

#66 Make power_robot and shutdown methods a part of spot.py
  bd_spot_wrapper/spot_wrapper/draw_square.py
  bd_spot_wrapper/spot_wrapper/keyboard_teleop.py
  bd_spot_wrapper/spot_wrapper/spot.py
  spot_rl_experiments/experiments/comparisons/gaze_all_objects.py
  spot_rl_experiments/experiments/comparisons/multiple_gaze.py
  spot_rl_experiments/experiments/comparisons/nav_compare.py
  spot_rl_experiments/spot_rl/baselines/go_to_waypoint.py
  spot_rl_experiments/spot_rl/envs/gaze_env.py
  spot_rl_experiments/spot_rl/envs/lang_env.py
  spot_rl_experiments/spot_rl/envs/mobile_manipulation_env.py
  spot_rl_experiments/spot_rl/envs/nav_env.py
  spot_rl_experiments/spot_rl/envs/place_env.py
  tests/hardware_tests/test_gaze_env.py
  tests/hardware_tests/test_nav_env.py
  tests/hardware_tests/test_place_env.py
Labels: CLA Signed

#62 High level skills for Habitat-llm integration
  bd_spot_wrapper/spot_wrapper/spot.py
  spot_rl_experiments/configs/config.yaml
  spot_rl_experiments/spot_rl/envs/base_env.py
  spot_rl_experiments/spot_rl/envs/lang_env.py
  spot_rl_experiments/spot_rl/envs/mobile_manipulation_env.py
  spot_rl_experiments/spot_rl/envs/place_env.py
  spot_rl_experiments/spot_rl/envs/skill_manager.py
  spot_rl_experiments/spot_rl/models/owlvit.py
Labels: bug, enhancement, CLA Signed

#60 Update installation documentation regarding missing weights error
  installation/ISSUES.md
Labels: documentation, CLA Signed

#72 Fix test_place env bug of incorrect list argument
  tests/hardware_tests/test_place_env.py
Labels: CLA Signed
