Repository facebookresearch/spot-sim2real, pull requests merged in 2024-03, with the labels that each got.

#136 Generalize atomic skill classes to use class Skill as interface
  bd_spot_wrapper/spot_wrapper/keyboard_teleop.py
  spot_rl_experiments/configs/config.yaml
  spot_rl_experiments/experiments/comparisons/gaze_all_objects.py
  spot_rl_experiments/experiments/comparisons/multiple_gaze.py
  spot_rl_experiments/experiments/comparisons/nav_compare.py
  spot_rl_experiments/spot_rl/envs/base_env.py
  spot_rl_experiments/spot_rl/envs/gaze_env.py
  spot_rl_experiments/spot_rl/envs/lang_env.py
  spot_rl_experiments/spot_rl/envs/mobile_manipulation_env.py
  spot_rl_experiments/spot_rl/envs/place_env.py
  spot_rl_experiments/spot_rl/envs/skill_manager.py
  spot_rl_experiments/spot_rl/examples/run_navigation.py
  spot_rl_experiments/spot_rl/examples/run_pick.py
  spot_rl_experiments/spot_rl/examples/run_place.py
  spot_rl_experiments/spot_rl/skills/README.md
  spot_rl_experiments/spot_rl/skills/atomic_skills.py
  tests/hardware_tests/configs/config.yaml
  tests/hardware_tests/test_gaze_env.py
  tests/hardware_tests/test_nav_env.py
  tests/hardware_tests/test_place_env.py
Labels: documentation, enhancement, CLA Signed

#118 Refactor spotqrdetector class and spot interface
  aria_data_loaders/aria_data_utils/aria_live_streamer.py
  aria_data_loaders/aria_data_utils/aria_streamer.py
  aria_data_loaders/aria_data_utils/episodic_memory_robotic_fetch.py
  bd_spot_wrapper/spot_wrapper/spot.py
  bd_spot_wrapper/spot_wrapper/spot_qr_detector.py
  perception_and_utils_root/perception_and_utils/perception/april_tag_pose_estimator.py
  perception_and_utils_root/perception_and_utils/perception/detector_wrappers/april_tag_detector.py
  perception_and_utils_root/perception_and_utils/perception/detector_wrappers/object_detector.py
  perception_and_utils_root/perception_and_utils/utils/conversions.py
  perception_and_utils_root/perception_and_utils/utils/generic_utils.py
  perception_and_utils_root/perception_and_utils/utils/math_utils.py
  spot_rl_experiments/configs/ros_frame_names.yaml
  spot_rl_experiments/experiments/skill_test/test_heurisitic_gaze.py
  spot_rl_experiments/experiments/skill_test/test_mobile_gaze.py
  spot_rl_experiments/spot_rl/envs/skill_manager.py
  spot_rl_experiments/spot_rl/skills/atomic_skills.py
  spot_rl_experiments/spot_rl/utils/utils.py
Labels: enhancement, CLA Signed

#148 Update OpenAI model
  spot_rl_experiments/spot_rl/llm/src/conf/llm/openai.yaml
  spot_rl_experiments/spot_rl/llm/src/rearrange_llm.py
Labels: CLA Signed

#145 Open drawer nyc
  bd_spot_wrapper/spot_wrapper/spot.py
  spot_rl_experiments/configs/config.yaml
  spot_rl_experiments/experiments/skill_test/test_open_close_drawer.py
  spot_rl_experiments/spot_rl/envs/base_env.py
  spot_rl_experiments/spot_rl/envs/open_close_drawer_env.py
  spot_rl_experiments/spot_rl/envs/place_env.py
  spot_rl_experiments/spot_rl/envs/skill_manager.py
  spot_rl_experiments/spot_rl/models/owlvit.py
  spot_rl_experiments/spot_rl/real_policy.py
  spot_rl_experiments/spot_rl/skills/atomic_skills.py
  spot_rl_experiments/spot_rl/utils/construct_configs.py
  spot_rl_experiments/spot_rl/utils/depth_map_utils.py
  spot_rl_experiments/utils/cparamopenclosedrawer.yaml
Labels: CLA Signed

#128 Intel RealSense D435 Payload Integration with Spot via Spot Core I/O
  .gitignore
  intel_realsense_payload_for_spotsim2real/Dockerfile
  intel_realsense_payload_for_spotsim2real/IntelRealSenseCameraInterface.py
  intel_realsense_payload_for_spotsim2real/README.md
  intel_realsense_payload_for_spotsim2real/bashrc.txt
  intel_realsense_payload_for_spotsim2real/caliberate_intel_with_gripper_cam.py
  intel_realsense_payload_for_spotsim2real/images_for_readme/spot-client.jpg
  intel_realsense_payload_for_spotsim2real/images_for_readme/spot_core_intel_realsense.drawio.png
  intel_realsense_payload_for_spotsim2real/intelrealsense_image_service.py
  intel_realsense_payload_for_spotsim2real/intelrealsensepayloadservice.service
  intel_realsense_payload_for_spotsim2real/makepythonexecutable[optional]/intelrealsense_image_service.spec
  intel_realsense_payload_for_spotsim2real/makepythonexecutable[optional]/pyinstallercommand.sh
  intel_realsense_payload_for_spotsim2real/makepythonexecutable[optional]/register_image_service_payload.spec
  intel_realsense_payload_for_spotsim2real/makepythonexecutable[optional]/spot-client.spec
  intel_realsense_payload_for_spotsim2real/register_image_service_payload.py
  intel_realsense_payload_for_spotsim2real/requirements.txt
  intel_realsense_payload_for_spotsim2real/spot_sim2real_integrationfn.py
  intel_realsense_payload_for_spotsim2real/startpayload.sh
  intel_realsense_payload_for_spotsim2real/visualizer.py
  spot_rl_experiments/spot_rl/utils/heuristic_nav.py
Labels: CLA Signed

#155 README image update
  intel_realsense_payload_for_spotsim2real/images_for_readme/spot_core_intel_realsense.drawio.png
Labels: CLA Signed
